stages:
  - build
  - test

build:
  stage: build
  script:
    - ./ci/build.csh

riscv_tests:
  stage: test
  script:
    - ./ci/rtl-riscv.csh

sequential_tests:
  stage: test
  script:
    - ./ci/rtl-sequential.csh

riscv_tests_rvc:
  stage: test
  script:
    - ./ci/rtl-riscv-rvc.csh

sequential_tests_rvc:
  stage: test
  script:
    - ./ci/rtl-sequential-rvc.csh
