stages:
  - build
  - test

before_script:
  - ./ci/setup_riscy.csh
  - ./ci/setup_zero.csh

rtl_riscy:
  stage: test
  script:
    - ./ci/rtl-riscy.csh

rtl_riscy_sequential:
  stage: test
  script:
    - ./ci/rtl_riscy_sequential.csh

rtl_riscy_rvc:
  stage: test
  script:
    - ./ci/rtl-riscy-rvc.csh

rtl_riscy_sequential_rvc:
  stage: test
  script:
    - ./ci/rtl-riscy_sequential-rvc.csh

rtl_zero:
  stage: test
  script:
    - ./ci/rtl-zero.csh

rtl_zero_sequential:
  stage: test
  script:
    - ./ci/rtl_zero_sequential.csh

rtl_zero_rvc:
  stage: test
  script:
    - ./ci/rtl-zero-rvc.csh

rtl_zero_sequential_rvc:
  stage: test
  script:
    - ./ci/rtl-zero_sequential-rvc.csh

rtl_micro:
  stage: test
  script:
    - ./ci/rtl-micro.csh

rtl_micro_sequential:
  stage: test
  script:
    - ./ci/rtl_micro_sequential.csh

rtl_micro_rvc:
  stage: test
  script:
    - ./ci/rtl-micro-rvc.csh

rtl_micro_sequential_rvc:
  stage: test
  script:
    - ./ci/rtl-micro_sequential-rvc.csh