stages:
  - build_riscy
  - test_riscy
  - build_zero
  - test_zero
  - build_micro
  - test_micro

build_riscy:
  stage: build_riscy
  script:
    - ./ci/setup_riscy.csh

build_zero:
  stage: build_zero
  script:
    - ./ci/setup_zero.csh

build_micro:
  stage: build_micro
  script:
    - ./ci/setup_zero.csh

rtl_riscy:
  stage: test_riscy
  script:
    - ./ci/rtl-riscy.csh

rtl_riscy_sequential:
  stage: test_riscy
  script:
    - ./ci/rtl-riscy-sequential.csh
  dependencies: build_riscy

rtl_riscy_rvc:
  stage: test_riscy
  script:
    - ./ci/rtl-riscy-rvc.csh

rtl_riscy_sequential_rvc:
  stage: test_riscy
  script:
    - ./ci/rtl-riscy-sequential-rvc.csh

rtl_zero:
  stage: test_zero
  script:
    - ./ci/rtl-zero.csh

rtl_zero_sequential:
  stage: test_zero
  script:
    - ./ci/rtl-zero-sequential.csh

rtl_zero_rvc:
  stage: test_zero
  script:
    - ./ci/rtl-zero-rvc.csh


rtl_zero_sequential_rvc:
  stage: test_zero
  script:
    - ./ci/rtl-zero-sequential-rvc.csh


rtl_micro:
  stage: test_micro
  script:
    - ./ci/rtl-micro.csh


rtl_micro_sequential:
  stage: test_micro
  script:
    - ./ci/rtl-micro-sequential.csh


rtl_micro_rvc:
  stage: test_micro
  script:
    - ./ci/rtl-micro-rvc.csh

rtl_micro_sequential_rvc:
  stage: test_micro
  script:
    - ./ci/rtl-micro-sequential-rvc.csh

