stages:
  - build
  - test

before_script:
  - ./ci/setup.csh

rtl_riscv:
  stage: test
  script:
    - ./ci/rtl-riscv.csh

rtl_sequential:
  stage: test
  script:
    - ./ci/rtl-sequential.csh

rtl_riscv_rvc:
  stage: test
  script:
    - ./ci/rtl-riscv-rvc.csh

rtl_sequential_rvc:
  stage: test
  script:
    - ./ci/rtl-sequential-rvc.csh

#############################################
#                                           #
#  Imperio Tests                            #
#                                           #
#############################################

imperio_riscv:
  stage: test
  script:
    - ./ci/imperio-riscv.csh

imperio_sequential:
  stage: test
  script:
    - ./ci/imperio-sequential.csh

imperio_riscv_rvc:
  stage: test
  script:
    - ./ci/imperio-riscv-rvc.csh

imperio_sequential_rvc:
  stage: test
  script:
    - ./ci/imperio-sequential-rvc.csh

imperio:
  stage: test
  script:
    - ./ci/imperio.csh

imperio_rvc:
  stage: test
  script:
    - ./ci/imperio-rvc.csh