stages:
  - build
  - test

before_script:
  - ./ci/setup.csh

riscv_tests:
  stage: test
  script:
    - ./ci/riscv-tests.csh

sequential_tests:
  stage: test
  script:
    - ./ci/rtl-sequential_tests.csh
