stages:
  - build
  - test

before_script:
  - ./ci/setup_riscy.csh

rtl_riscy:
  stage: test
  script:
    - ./ci/rtl-riscy.csh

rtl_riscy_sequential:
  stage: test
  script:
    - ./ci/rtl-riscy-sequential.csh

rtl_riscy_rvc:
  stage: test
  script:
    - ./ci/rtl-riscy-rvc.csh

rtl_riscy_sequential_rvc:
  stage: test
  script:
    - ./ci/rtl-riscy-sequential-rvc.csh

rtl_zero:
  stage: test
  script:
    - ./ci/rtl-zero.csh
  before_script:
    - ./ci/setup_zero.csh

rtl_zero_sequential:
  stage: test
  script:
    - ./ci/rtl-zero-sequential.csh
  before_script:
    - ./ci/setup_zero.csh

rtl_zero_rvc:
  stage: test
  script:
    - ./ci/rtl-zero-rvc.csh
  before_script:
    - ./ci/setup_zero.csh


rtl_zero_sequential_rvc:
  stage: test
  script:
    - ./ci/rtl-zero-sequential-rvc.csh
  before_script:
    - ./ci/setup_zero.csh


rtl_micro:
  stage: test
  script:
    - ./ci/rtl-micro.csh
  before_script:
    - ./ci/setup_zero.csh


rtl_micro_sequential:
  stage: test
  script:
    - ./ci/rtl-micro-sequential.csh
  before_script:
    - ./ci/setup_zero.csh


rtl_micro_rvc:
  stage: test
  script:
    - ./ci/rtl-micro-rvc.csh
  before_script:
    - ./ci/setup_zero.csh

rtl_micro_sequential_rvc:
  stage: test
  script:
    - ./ci/rtl-micro-sequential-rvc.csh
  before_script:
    - ./ci/setup_zero.csh

